# Be sure to install these packages before running this script
# They can be installed either with the intall.packages() function
# or with the 'Packages' pane in RStudio

# load general-use packages
library("dplyr")
library("tidyr")
library("knitr")
library("ggplot2")

# These are the primary packages well use to clean and analyze the data
# this package needs to be installed from bioconductor -- it's not on CRAN
# see info here: https://benjjneb.github.io/dada2/dada-installation.html
library("dada2")

# And this to visualize our results
# it also needs to be installed from bioconductor
library("phyloseq")

# load in data files generated by dada
# save necessary files from dada pipeline to use with phyloseq
load("output/dada-results/seqtable.Rda")
load("output/dada-results/taxatable.Rda")

# Next we want to read in the metadata file so we can add that in too
# This is not a csv file, so we have to use a slightly different syntax
# here the `sep = "\t"` tells the function that the data are tab-delimited
# and the `stringsAsFactors = FALSE` tells it not to assume that things are
# categorical variables
metadata_in <- read.csv(paste0("data/metadata/",
                                 "illumina_sample_metadata_for_phyloseq.csv"),
                          header = TRUE,
                          stringsAsFactors = FALSE,
                          row.names = 5) # sets sample IDs to row names

# Construct phyloseq object (straightforward from dada2 outputs)
phyloseq_obj <- phyloseq(otu_table(sequence_table_nochim,
                                   taxa_are_rows = FALSE), # sample-spp matrix
                         sample_data(metadata_in), # metadata for each sample
                         tax_table(taxa)) # taxonomy for each sequence variant

# save phyloseq and melted_phyloseq objects to use in the Rmd file
save(phyloseq_obj, file = "output/phyloseq_obj.Rda")

